modLoader="javafml" 
loaderVersion="[25,)"
issueTrackerURL="https://github.com/SR2610/MicroMods/issues"
logoFile="creeperconfetti.png"
[[mods]]
modId="creeperconfetti"
version="${file.jarVersion}"
displayName="Creeper Confetti"
#updateJSONURL="http://myurl.me/"
displayURL="https://minecraft.curseforge.com/projects/creeper-confetti"
credits="The Forge Team"
authors="SR2610"
description='''
A mod that replaces the Creeper explosion with Confetti
'''

## A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
#[[dependencies.examplemod]] 
#    # the modid of the dependency
#    modId="forge" 
#    # Does this dependency have to exist - if not, ordering below must be specified
#    mandatory=true 
#    # The version range of the dependency
#    versionRange="[25,)" 
#    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
#    ordering="NONE"
#    # Side this dependency is applied on - BOTH, CLIENT or SERVER
#    side="BOTH"
## Here's another dependency
#[[dependencies.examplemod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.13.2]"
#    ordering="NONE"
#    side="BOTH"