modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/SR2610/MicroMods/issues"
logoFile="creeperconfetti.png"
[[mods]]
modId="creeperconfetti"
version="${file.jarVersion}"
displayName="Creeper Confetti"
#updateJSONURL="http://myurl.me/"
displayURL="https://minecraft.curseforge.com/projects/creeper-confetti"
credits="The Forge Team"
authors="SR2610"
description='''
A mod that replaces the Creeper explosion with Confetti
'''